version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: locker_app
    ports:
      - '5432:5432'
  api:
    image: node:18
    working_dir: /app
    volumes:
      - ../../apps/api:/app
    command: sh -c "npm install && npm run prisma:migrate && npm run dev"
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/locker_app
    depends_on:
      - db
